plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.huancheng.checkin'
    compileSdk 34

    defaultConfig {
        applicationId "com.huancheng.checkin"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        python {
            buildPython "python3"
            pip {
                install "flask"
                install "waitress"
                install "requests"
            }
        }

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
